import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home({ posts }) {
    console.log('-- client --');
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
          {
              posts?.map(post => {
                  return (
                      <Link key={post.id} href={post.Slug}>
                          <a className={styles.description}>
                              <h3>{ post.Title }</h3>
                              <p>{ post.User.username }</p>
                          </a>
                      </Link>
                  );
              })
          }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

/**
 * getStaticProps used for Static-Site Generation (SSG)
 *
 * @returns {Promise<{props: {posts: any}}>}
 */
export async function getStaticProps() {
    console.log('-- server --');
    
    const response = await fetch('http://localhost:1337/posts');
    const posts = await response.json();
    
    console.log(posts);
    
    return {
        props: { posts }
    }
}